export default {
    SHOW_LOADING: 'SHOW_LOADING',
    HIDE_LOADING: 'HIDE_LOADING',
    HIDE_TUTORIAL: 'HIDE_TUTORIAL',
    OPEN_POPUP_ERROR: 'OPEN_POPUP_ERROR',
    CLOSE_POPUP_ERROR: 'CLOSE_POPUP_ERROR',
    ADD_STACK: 'ADD_STACK',
    TOGGLE_PHONE_CODE_PICKER: 'TOGGLE_PHONE_CODE_PICKER',
};
