export default {
    CLEAR_USER: 'CLEAR_USER',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_ANONYMOUS_USER: 'UPDATE_ANONYMOUS_USER',
    UPDATE_USER_TOKEN: 'UPDATE_USER_TOKEN',
    UPDATE_ANONYMOUS_USER_TOKEN: 'UPDATE_ANONYMOUS_USER_TOKEN',
    UPDATE_SETTINGS: 'UPDATE_SETTINGS'
}